/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package protobufhandler;

import burp.api.montoya.BurpExtension;
import burp.api.montoya.MontoyaApi;
import burp.api.montoya.logging.Logging;

//Burp will auto-detect and load any class that extends BurpExtension.
public class App implements BurpExtension {

    @Override
    public void initialize(MontoyaApi api) {
        Logging logging = api.logging();
        api.extension().setName("Protobuf Handler");

        AppHandler handler = new AppHandler(api);
        api.http().registerHttpHandler(handler);

        logging.logToOutput("Successfully loaded Protobuf Handler v0.0.1");
    }
}